# DATASTRUCTURES
1. Series:  key difference between Series and ndarray is that operations between Series automatically align the data based on label.

In [20]:
import pandas as pd

sList = pd.Series([1,2,3],index = [1,2,3])
sDict = pd.Series({1:'object1',2:'Object2'})
sDictIdx = pd.Series({"a": 0.0, "b": 1.0, "c": 2.0},index = ['b','c','d'])
sScalar = pd.Series(5,index = [1,2,3,4],dtype = 'int64')
sNDarray = pd.Series([[1,2,3,'a'],[4,5,6]],index = ['a','b'])

print(sList)
print(sDict)
print(sDictIdx)
print(sScalar)
print(sNDarray)

print(sNDarray['a'][0])
sList['new'] = 7
print(sList)

print(sList+sScalar)

1    1
2    2
3    3
dtype: int64
1    object1
2    Object2
dtype: str
b    1.0
c    2.0
d    NaN
dtype: float64
1    5
2    5
3    5
4    5
dtype: int64
a    [1, 2, 3, a]
b       [4, 5, 6]
dtype: object
1
1      1
2      2
3      3
new    7
dtype: int64
1      6.0
2      7.0
3      8.0
4      NaN
new    NaN
dtype: float64

2. DATAFRAMES

In [27]:
dfList = pd.DataFrame([[1,2,3,4,5,6],[3,4,5,'6',8]],index = ['a','b'],columns=[1,2,3,4,5,6])
dfList

   1  2  3  4  5    6
a  1  2  3  4  5  6.0
b  3  4  5  6  8  NaN

In [30]:
d = {'one':[1,2],'two':[3,4],'three':[5,6]}
df = pd.DataFrame(d,index = ['a','b'])
df

   one  two  three
a    1    3      5
b    2    4      6

In [32]:
print(df.index)
print(df.columns)

Index(['a', 'b'], dtype='str')
Index(['one', 'two', 'three'], dtype='str')

In [34]:
data = [{"a": 1, "b": 2}, {"a": 5, "b": 10, "c": 20}]
dframe = pd.DataFrame(data,index = ['first','second'])
dframe

        a   b     c
first   1   2   NaN
second  5  10  20.0

2.1 Column selection, addition and deletion